### ISSUE TITLE
Build docs are not complete

### ISSUE THREAD

**Issue by jdatcmd** [commandprompt/pgmanage#125]
Running Ubuntu there is a lot of assumptions that are made including users having poetry, psutil or even django installed.

**Comment by eug3nix** [comment]
Hi.
I have updated the instructions in BUILD.md file with the necessary steps on how to produce release packages for Linux and Windows platforms.

The README.md was also updated with the correct instructions on how to run a local development copy. Outdated and irrelevant instructions were removed from that file.
