### ISSUE TITLE
.pgpass support

### ISSUE THREAD

**Issue by jdatcmd** [commandprompt/pgmanage#130]
As the standard way to store connection strings/passwords for postgresql is .pgpass, should we auto support a .pgpass in the launching users connection strings?

**Comment by eug3nix** [comment]
We do support .pgpass for postgres connections that are not using connection string.
It seems to be impossible to connect to the database using connection string AND be able to use pgpass file.
The details of pgpass handling logic should be documented in the pgmanage handbook

**Comment by eug3nix** [comment]
Added a note about this in the docs.
