### ISSUE TITLE
pgmanage version server ?

### ISSUE THREAD

**Issue by Geronium** [commandprompt/pgmanage#148]
hello,

It's really nice to take over the omnidb project. And to give it a follow-up.

Is it possible to do the same for omnidb version server?

Thank you

**Comment by eug3nix** [comment]
Hi.
While it is still technically possible to run pgmanage in a sever-based mode, this use case is not well tested and not officially supported yet. We are planning to put more work into this in the future. The instructions provided in README are basically describing how to run pgmanage in web-app mode https://github.com/commandprompt/pgmanage#run-your-local-development-copy-of-pgmanage-on-ubuntu.

**Comment by Geronium** [comment]
Thanks, i just finish to build the docker image, i will try it. 

If someone needs it, he can find here the dockerfile (i modified the dockerfile of omnidb 3.0.6 for pgmanage)  

[Dockerfile.tar.gz](https://github.com/commandprompt/pgmanage/files/11885421/Dockerfile.tar.gz)
