### ISSUE TITLE
Default ssl mode when 'Add New Connection"

### ISSUE THREAD

**Issue by Lucikr** [commandprompt/pgmanage#149]
Steps to reproduce:
1.Navigate to Manage connections modal..
2.Click on 'Add' button and select 'Connection'.

Observed results:
SSL mode is not preselected with default option for  PostgreSQL type.

Expected:
SSL mode with option "prefer" should be preselected.

![Screenshot from 2023-06-14 12-37-52](https://github.com/commandprompt/pgmanage/assets/65090602/8394e56d-46f3-4dfe-bab1-c298948d1fa2)

**Comment by eug3nix** [comment]
verified.
