### ISSUE TITLE
SSL option does not change

### ISSUE THREAD

**Issue by Lucikr** [commandprompt/pgmanage#150]
Steps to reproduce:
1.Navigate to Manage connections modal..
2.Click on 'Add' button and select 'Connection'.
3.Change the name of Connection.
4.Switch between different database types.

Observed result:
SSL mode option is empty and does not change.

Expected:
The SSL mode option should automatically change its value to a default option based on the specified database type.

![Screenshot from 2023-06-14 12-44-28](https://github.com/commandprompt/pgmanage/assets/65090602/ef56da6c-f33f-4198-8789-c20a995e8683)

**Comment by eug3nix** [comment]
verified.
