### ISSUE TITLE
make auto-complete setting "sticky"

### ISSUE THREAD

**Issue by ccurvey** [commandprompt/pgmanage#200]
At the moment, auto-complete is set to "on" each time I start the app.   It would be great if PgManage could remember my setting (I want it off...permanently) from session to session.

**Comment by eug3nix** [comment]
Hi @ccurvey.
Since this seems to be a reasonable UX enhancement we have planned to include it into the next release.
Speaking keeping the autocomplete off - are there any reasons why you do that (except that the current implementation is buggy and sometimes getting in the way during the editing process) ?

**Comment by ccurvey** [comment]
I know my database really well, so I can type faster than the autocomplete, and having the autocomplete window appearing and disappearing is distracting.

Some other notes (since you're going to be in there anyway)....

If I do need auto-complete (for example, I'm working on an existing project for the 1st time), the autocomplete needs to stay up for long enough for me to look at the list of tables and see what is interesting.

If I choose from the auto-complete, I'm not a fan of it adding the schema to the front of the table name.  I don't use non-public schemas, but some folks do, so that might be best implemented as a user setting.

**Comment by eug3nix** [comment]
This feature has been implemented in Pgmanage 1.0b3

**Comment by ccurvey** [comment]
this is not working (at least on Windows).  

1. Connect to database
2. turn off autocomplete 
3. run query
4. Close PgManage
5. Start PgManage

Autocomplete is enabled.

**Comment by eug3nix** [comment]
This issue has been fixed in version 1.0rc1, we have also changed the autocomplete setting, now is stored on a per-connection basis (it was a global setting previously)
Thanks!
