### ISSUE TITLE
sql window in query tab hangs

### ISSUE THREAD

**Issue by ccurvey** [commandprompt/pgmanage#201]
I don't know what causes it, but from time to time the SQL editor window on a query tab becomes unresponsive.    I can type all I want and no character appear.  

The only fix I have found for it is to restart the app.

**Comment by eug3nix** [comment]
Hi @ccurvey . I am happy to announce that we've released a new version of PgManage which includes numerous new features and bugfixes, including fixes for SQL autocomplete.
You can download new binaries here:
https://www.commandprompt.com/products/pgmanage/
