### ISSUE TITLE
can we auto-reconnect?  or at least fail loudly?

### ISSUE THREAD

**Issue by ccurvey** [commandprompt/pgmanage#230]
1.  I open a connection to a server and do some work. Life is good
2. I get called away, so I close my laptop for a while
3. I come back, go to my PgManage window, and try to run a query...and it just hangs forever.  I have to close the connection in the left nav.

I realize that the connection is dropped when I close the laptop and go away.  Would it be possible to have PgManage detect that the connection has been lost, and either try to reconnect silently (best!) or put up a window informing me that I need to reconnect?

**Comment by commandprompt** [comment]
Sure. We are aware that there are issues when app front-end loses its DB session with the back-end part of the app. There will be improvements for that in the next release.
Thanks.
