### ISSUE TITLE
can't use connection string on Windows version

### ISSUE THREAD

**Issue by ccurvey** [commandprompt/pgmanage#236]
I'm trying to use the Windows version of PgManage, and I can't paste (or type) my connection string into the text box on the "add connection" form.  The field just seems to be disabled/read-only.

**Comment by eug3nix** [comment]
I've checked that and can confirm that the issue exists.
The connection string input is only available if the top part of the connection form is empty.
We have recently introduced a new feature which auto-populates the database server port number with a default value, this affects the connection string field. As a workaround you can clear the port number field and the connection string should become available for editing.
I need to think on better solution for that.

**Comment by eug3nix** [comment]
Hi @ccurvey . The fix for this issue was included in 1.0rc1 build, which can be downloaded here:
https://www.commandprompt.com/products/pgmanage/
