### ISSUE TITLE
"copy" copies the full SQL window, not just the highlighted text

### ISSUE THREAD

**Issue by ccurvey** [commandprompt/pgmanage#268]
1) write a query like this:

```
select *
from foobar
where id = 12345
```

2) highlight the "12345"

3) right-click the selection, choose copy.   the full text of the window is copied.

(ctrl-c seems to work properly)

**Comment by eug3nix** [comment]
Thanks for reporting this issue
We will include a fix in the next release.

**Comment by eug3nix** [comment]
Hi @ccurvey , I have just uploaded binaries for Release Candidate 2 which include fix for this issues (including lots of other changes)
You can find the binaries in the releases section of the project: https://github.com/commandprompt/pgmanage/releases/tag/1.0.0rc2

We will be releasing an official 1.0 version on the next week.
