### ISSUE TITLE
'View content' context menu item doesn't work properly in Monitoring Dashboard grid widget if cell is a number

### ISSUE THREAD

**Issue by plucik** [commandprompt/pgmanage#354]
steps to reproduce:
1.Open database connection.
2.Open monitoring Dashboard tab.
3.Right click on grid widget cell which contains only number.
4.Select 'View content'.

expected:
View content modal is opened.

observed:
Nothing happens.
After this error, 'View content' doesn't work even on other cells with string values.

**Comment by eug3nix** [comment]
verified.
