### ISSUE TITLE
Edit data doesn't work on mysql dialect in databases other than default one for connection

### ISSUE THREAD

**Issue by plucik** [commandprompt/pgmanage#410]
steps to reproduce:
1.launch pgmanage
2.open mysql connection
3.Open database that isn't in 'Selected database'.
4.Try to 'Edit Data'  on table from this database(for ex. classicmodels database).

observed:
The toast with error - (1146, "Table 'mysql.dept_manager' doesn't exist") is shown.

expected:
Data editor tab opens with loaded table data

**Comment by eug3nix** [comment]
fixed.
