### ISSUE TITLE
data grid - Adaptive layout bug

### ISSUE THREAD

**Issue by plucik** [commandprompt/pgmanage#412]
Steps to reproduce:
1.Open pgmanage connection
2.Run a query on a table that has more than 50 records..
3.Click Fetch All button
4.Scroll down so initial rows is not visible.
5.Change layout to Fit Content.
6.Change layout to Adaptive.
Observed result:
![Screenshot from 2024-06-18 11-09-07](https://github.com/commandprompt/pgmanage/assets/152685381/2068d28e-a4da-4b95-9bec-4e8272a74142)
Expected result:
![Screenshot from 2024-06-18 11-09-30](https://github.com/commandprompt/pgmanage/assets/152685381/586241c8-4692-42ee-8361-f79ca3f5fc2d)

**Comment by eug3nix** [comment]
fixed.
