### ISSUE TITLE
Connection String  Oracle

### ISSUE THREAD

**Issue by jdelramirez** [commandprompt/pgmanage#431]
Hi guys, im trying to use connection string format in Oracle, but is not working, all time saying is wrong 

![image](https://github.com/user-attachments/assets/a1042c8e-5632-4aa1-a502-bf2a1cac57f8)

the format im using is  :  oracle://usertest:password@10.1.1.1:1521/servicetest

:(

Any help ?

Thanks !

**Comment by eug3nix** [comment]
Hello.
The 1.1 release includes a fix for this issue:
https://github.com/commandprompt/pgmanage/releases/tag/1.1

**Comment by jdelramirez** [comment]
Good morning, I am still encountering the same error. 

![image](https://github.com/user-attachments/assets/bc35fc84-b02d-46b4-b585-8c227b89b6db)

I have downloaded the version you indicated, 1.1 for Unix, followed all the same steps, and installed the requirements, but I cannot get the connection string to work correctly. 

is a change of this file ? ./app/include/OmniDatabase/Oracle.py ?

/python3.9/site-packages/oracledb-1.3.1.dist-info


Could you please assist me? Thank you
