### ISSUE TITLE
No support for IPv6 addresses

### ISSUE THREAD

**Issue by steffann** [commandprompt/pgmanage#434]
### A quick summary and/or background

When crating a new connection IPv6 addresses are not accepted as a server address:

<img width="1136" alt="image" src="https://github.com/user-attachments/assets/73843429-bce9-4b66-ba1d-5c21a6eef932">

It looks like this is just a user interface error, because using an IPv6 address in the connection string does work:

<img width="1136" alt="image" src="https://github.com/user-attachments/assets/2de3cd70-4ecf-4b3f-a4ac-23fb4637484b">

### PgManage flavor you are using (app or server) and version

This is the app. I have no idea which version this is, as I can't find a version number displayed anywhere in the app. I downloaded it on 2024-07-21.

### Operating system and version

This is macOS Sonoma 14.5 on an M1.

### Steps to reproduce

Create a new connection with a server reachable over IPv6.

### What you expected would happen

I expect IPv6 to be supported.

### What actually happens

The UI tells me that it's an invalid IPv6 address.

**Comment by eug3nix** [comment]
Hi.
Thanks for a detailed issue report.
The current validation logic expects IPv4 address in that field.
Based on your feedback we will extend the validation pattern in the next release.

Speaking of the application version - you can see it on a startup splash screen, it is also displayed in the utilities menu (the expandable toolbar which is shown when you click on the top-right button in the UI).
The app builds which we distribute also include version number in the file names.\

Sincerely,
Eugene
