### ISSUE TITLE
Make Unix Domain Sockets usage more intuitive in the Connections Manager

### ISSUE THREAD

**Issue by eug3nix** [commandprompt/pgmanage#437]
It should be more obvious that unix sockets could also be used

> While I don't personally think this'll be useful for me as it doesn't seem to support unix socket connections, the company that's providing it is Command Prompt, Inc.
> They've been involved with the PostgreSQL Community for at least 2 decades (as have I), so it's super unlikely this is something malicious.
source: https://news.ycombinator.com/item?id=41025101

**Comment by eug3nix** [comment]
Hey @justinclift I am happy to announce that the new Pgmanage release which includes the change you suggested has been made public: https://github.com/commandprompt/pgmanage/releases/tag/1.1.1
Thank you for your feedback!

**Comment by justinclift** [comment]
Awesome @eug3nix, hopefully that makes it a bunch easier for people to use it with (at least) PostgreSQL. :smile:
