### ISSUE TITLE
Query/Console tab bug

### ISSUE THREAD

**Issue by plucik** [commandprompt/pgmanage#447]
There is a significant bug that makes the Query and Console tab not draggable and laggy after certain interactions:
1.Open the Query/Console tab.
2.Run a query that returns more than 50 records.
3.Drag the horizontal scrollbar a little bit down or up.
4.Run the query again.
After this, the app becomes unusable and laggy, and the fetch buttons do not always show up.

**Comment by eug3nix** [comment]
verified.
