### ISSUE TITLE
"Discard changes" modal appears after closing connection tab

### ISSUE THREAD

**Issue by plucik** [commandprompt/pgmanage#476]
Steps to reproduce:
1.Open connection
2.Create new Query Tab
2.Type query in created Query Tab.
3.Click on Explain tab in nav tabs below the action buttons.
4.Close the connection.

Observed result:
Connection tab is closed."Discard changes" modal appears.

Expected result:
Connection tab is closed.

**Comment by eug3nix** [comment]
verified
