### ISSUE TITLE
Test connection use ssh key/database password from database even if it was cleared by user on front-end

### ISSUE THREAD

**Issue by plucik** [commandprompt/pgmanage#486]
Steps to reproduce:
1.Open "Manage Connections" modal
2.Go to existing connection which requires password.
3.Click on red circle xmark inside password input.
4.Click on "Test" button.

Observed result:
Toast notification with "Connection successful" appeared.

Exped result:
Error toast notification regarding empty password.

**Comment by eug3nix** [comment]
verified
