### ISSUE TITLE
Request race condition on connection start

### ISSUE THREAD

**Issue by plucik** [commandprompt/pgmanage#494]
There is an issue after this change - ac44c19cd902a98773a3e90ccea80108ce5b0880 where on connection start, multiple request try
to use same database connection  causing errors.
I am not sure this is the the real problem, so further investigation may be needed.
![Screenshot from 2024-09-25 17-30-12](https://github.com/user-attachments/assets/e5bd80cb-70c4-4fe1-a954-d70aaeeccf44)

**Comment by eug3nix** [comment]
fixed.
