### ISSUE TITLE
cannot decrypt password

### ISSUE THREAD

**Issue by ccurvey** [commandprompt/pgmanage#513]
I save my passwords in PgManage...suddenly I have to re-type them because:

> Failed to decrypt the saved password. Error: 'utf-8' codec can't decode bytes in position 0-1: invalid continuation byte

I can type in the password again, check the "save password" box, and connect.    But if I quit PgManage and come back in, I get the error again

**Comment by ccurvey** [comment]
Version: 8.12
OS: Ubuntu 24.04, fully patched w/ MATE

![pgmanage-password](https://github.com/user-attachments/assets/3191a38e-03d9-4f62-b464-13e0eeae9a9e)

I'm not cool enough to do the video thing, but this happens after startup as soon as I click on the twisty for my server in the tree view on the left.

**Comment by eug3nix** [comment]
This is the screenshot of PgAdmin4, not PgManage. I am not sure how I can help with that tbh.
Am I missing something?

**Comment by ccurvey** [comment]
Facepalm!  I filed a bug for the wrong project!  (What an original mistake!)
