### ISSUE TITLE
scroll vs zoom when looking at explain graph

### ISSUE THREAD

**Issue by ccurvey** [commandprompt/pgmanage#541]
There are no scrollbars on the window that shows the graph for the explain plan.   Using the scroll wheel on my mouse zooms the window.  This gets worse if you open a node in the graph to see the details, as it may move some of the graph out of the viewport with no way to see it again.  (Well, you can scroll until it is very small...but then I put my face right up to the monitor and have to clean the nose grease off the screen.)

**Comment by eug3nix** [comment]
Hi @ccurvey. The explain plan and ERD graphs are draggable, so no scrollbars is needed.
We have released PgManage v1.2 btw, so feel free to check it out.

Cheers!

**Comment by ccurvey** [comment]
> ERD graphs are draggable

Never noticed that.  Thanks!

> We have released PgManage v1.2 btw, so feel free to check it out.

Very pretty!  Thank you
