### ISSUE TITLE
Middle mouse click on element with href opens new tab default browser

### ISSUE THREAD

**Issue by plucik** [commandprompt/pgmanage#543]
Per peer review feedback.

> When closing tabs, I instinctively middle mouse click anywhere on the tab like I do in browsers, but when doing that in pgmanage, it opens a new tab in whatever my last active web browser is, which takes me to a login screen for pgmanage. I keep forgetting that I can't do that so I open a lot of tabs.

We should prevent this default behaviour.

**Comment by eug3nix** [comment]
verified
