### ISSUE TITLE
Few database tabs get highlighted, even though only one active tab is possible

### ISSUE THREAD

**Issue by plucik** [commandprompt/pgmanage#570]
Steps to reproduce:
1.Open a new connection.
2.Create a new query tab.
3.Close the Terminal tab.

Expected result:
The Terminal tab is removed, leaving only one active tab.

Observed result:
The Terminal tab is removed, but two tabs remain active.

![image](https://github.com/user-attachments/assets/833abeb3-1202-4419-8112-64140c964b4c)

**Comment by eug3nix** [comment]
verified.
