### ISSUE TITLE
Create connections first

### ISSUE THREAD

**Issue by dimlev** [commandprompt/pgmanage#86]
Hi,

I am trying to connect to a local postgresql server and i am getting error "Create connections first". There is one connection (see screenshot) Also "test" does not seem to do anything. 

Screenshot of the connection:
https://imgur.com/VbYC2If.png

PgManage flavor you are using (app or server) and version
pgmanage-1.0.0a.AppImage

Operating system and version:
Arch Linux 6.1.12-arch1-1

**Comment by eug3nix** [comment]
Hi dimlev. Thanks for reporting the issue.

I would like to get some more details on how to reproduce it.
Can you please provide the list of exact steps one need to take to get this error?

Note: you may need to start with a clean app database in order to perform the necessary steps, to do that - just remove ~/.pgmanage/pgmanage-app dir.

**Comment by dimlev** [comment]
I found the following errors in the terminal (sorry but i didn't see them last time):

```
[186175:186175:0225/092856.512481:ERROR:gl_angle_util_vulkan.cc(17)] Failed to retrieve EGLDisplay
[186175:186175:0225/092856.512528:ERROR:vulkan_instance.cc(91)] Failed to get vkGetInstanceProcAddr pointer from ANGLE.
[186179:186186:0225/092902.076020:ERROR:cert_verify_proc_builtin.cc(592)] No net_fetcher for performing AIA chasing.
[186179:186184:0225/092910.197781:ERROR:cert_verify_proc_builtin.cc(592)] No net_fetcher for performing AIA chasing.
```

So perhaps a certificate error and it is not able to communicate with the server some times?

**Comment by eug3nix** [comment]
These errors are not critical and are emitted by nwjs runtime, you can ignore them.
More info https://chromium-review.googlesource.com/c/chromium/src/+/2976423\

If you have the steps to reproduce the original issue please provide those, I'll be happy to investigate and fix the issue.

**Comment by dimlev** [comment]
Hi @eug3nix 

Sure here are the steps:

- I just started the app for the first time.
- Entered a master password twice as instructed.
- Got 'Master password created.'
- Clicked on connections / add / connection
- Entered the details you can see in the screenshot
- Clicked on test - nothing happens
- Clicked on save - nothing seems to be happening.
- Click on save again - nothing seems to be happening. Now i am thinking ok let me close the dialog and try again
- Clicked on x to close the connection dialog
- Clicked on connections (left menu) again. Apparently the connection was saved.
- Selected the previously saved connection.
- Clicked on test - nothing happens
- Clicked on connect - the popup closes but nothing else happens.
- Close the popup
- Restart the app
- Enter the master password
- Clicked on connections
- Selected the connection previously created
- Click on test - nothing happens
- Click on connect - the popup closes and i get the error "Create connections first."

Thank you for taking the time btw

**Comment by dimlev** [comment]
Apparently there is a log file lol. It's more helpful:

```
[02/25/2023 08:53:54] INFO [app.Init:484] Starting server PgManage 1.0.0a at 127.0.0.1:8000.
[02/25/2023 08:53:56] INFO [app.views.login:120] User "admin" logged in.
[02/25/2023 09:01:08] ERROR [django.request:222] Internal Server Error: /test_connection/
Traceback (most recent call last):
  File "django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "app/views/memory_objects.py", line 48, in wrap
  File "app/views/connections.py", line 236, in test_connection
  File "OmniDatabase/__init__.py", line 53, in InstantiateDatabase
    return PostgreSQL(p_server, p_port, p_service, p_user, p_password, p_conn_id, p_alias, p_application_name, p_conn_string, p_parse_conn_string)
  File "OmniDatabase/PostgreSQL.py", line 104, in __init__
    self.v_connection = Spartacus.Database.PostgreSQL(self.v_active_server, self.v_active_port, self.v_active_service, self.v_active_user, self.v_password, p_application_name, p_conn_string)
  File "Spartacus/Database.py", line 1332, in __init__
    raise Spartacus.Database.Exception("PostgreSQL is not supported. Please install it with 'pip install Spartacus[postgresql]'.")
app.include.Spartacus.Database.Exception: PostgreSQL is not supported. Please install it with 'pip install Spartacus[postgresql]'.
```

**Comment by eug3nix** [comment]
Oh, that's interesting... Thank you for providing the logs. I'll take a look at this on the next week.
Perhaps something is missing on your system and the .AppImage does not have that "something" either (it should be self-contained by design).

**Comment by dimlev** [comment]
Yes, it works now.

Thank you @eug3nix
