### ISSUE TITLE
unclear what pgmanage does, or whom it is meant to be usefull for

### ISSUE THREAD

**Issue by vrms** [commandprompt/pgmanage#87]
I stumbled over this and fail to get what it actually does. Maybe some sort of dBeaver-ish thing ? 

On the docs it has a [big whole on that part as well](https://pgmanage.readthedocs.io/en/latest/en/01_introduction.html). I think it is worth filling that gap, maybe even before doing anything else.

--- 

A big thumbs up for publishing as AppImage though. Highly appreciated.

**Comment by eug3nix** [comment]
Hi @vrms
I am glad to announce that we have released pgmanage 1.0b along with the documentation updates.
The updated handbook was published to the URL mentioned in my comment above.
The new pgmanage release can be downloaded here: https://www.commandprompt.com/products/pgmanage/

Sincerely,
Eugene
